name: myapp
description: A new Flutter project.

publish_to: 'none' # Cette ligne empêche la publication accidentelle sur pub.dev. Supprimez-la si vous souhaitez publier sur pub.dev.

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ # Assurez-vous d'avoir un dossier "assets" contenant vos images
